language: python

python:
 - 2.7

env:
 - TOXENV=py26
 - TOXENV=py27
 - TOXENV=py31
 - TOXENV=py32
 - TOXENV=py33
 - TOXENV=py34
 - TOXENV=pypy
 - TOXENV=flake8

before_install:
 - if [[ $(echo "$TOXENV" | egrep -c "(py3[14])") != 0 ]]; then sudo add-apt-repository -y ppa:fkrull/deadsnakes; fi;
 - if [[ $(echo "$TOXENV" | egrep -c "(py3[14])") != 0 ]]; then sudo apt-get update -qq; fi;
 - if [[ "$TOXENV" == "py31" ]]; then sudo apt-get install -y python3.1; fi;
 - if [[ "$TOXENV" == "py34" ]]; then sudo apt-get install -y python3.4; fi;
 - if [[ "$TOXENV" == "pypy" ]]; then sudo apt-get install -y pypy; fi;

install:
 - if [[ $(echo "$TOXENV" | egrep -c "(py31)") != 0 ]]; then pip install virtualenv==1.7.2 tox==1.3; fi;
 - if [[ $(echo "$TOXENV" | egrep -c "(py31)") == 0 ]]; then pip install tox; fi;

script:
 - tox

notifications:
  email:
    - matt@sivel.net

